# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Area X 
tagline:             'Exploring The Petri-dish That Is The World'
description:         ''
url:                 http://AreaX.bio
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              S. Cerevisae
  url:               http://AreaX.bio
  email:             nothing@themome.nt

# Custom vars
version:             1.0.0
