# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Catapult Bio 
tagline:             'Exploring The Frontiers'
description:         ''
url:                 http://catapult.bio
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              S. Cerevisae
  url:               http://catapult.bio
  email:             nothing@themome.nt

# Custom vars
version:             1.0.0
